AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI Governance - Compute Infrastructure (App Runner)'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging

  GitHubRepository:
    Type: String
    Default: Episteme-Foundation/ai-governance
    Description: GitHub repository (owner/repo)

  # Note: ECR repository 'ai-governance' must exist before deploying this stack
  # Secrets are loaded from AWS Secrets Manager at runtime
  # Secret name: ai-governance/app-config

Resources:
  # IAM Role for App Runner to access ECR
  AppRunnerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ai-governance-apprunner-access
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  # IAM Role for App Runner instance (needs Secrets Manager access)
  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ai-governance-apprunner-instance
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:ai-governance/*'

  # App Runner Service
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: ai-governance
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerAccessRole.Arn
        AutoDeploymentsEnabled: false
        ImageRepository:
          ImageIdentifier: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ai-governance:latest'
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: '3000'
            RuntimeEnvironmentVariables:
              - Name: NODE_ENV
                Value: !Ref Environment
              - Name: PORT
                Value: '3000'
              - Name: AWS_REGION
                Value: !Ref AWS::Region
              - Name: AWS_SECRET_NAME
                Value: ai-governance/app-config
              - Name: GITHUB_REPOSITORY
                Value: !Ref GitHubRepository
      InstanceConfiguration:
        Cpu: '1024'
        Memory: '2048'
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /health
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5

Outputs:
  ServiceUrl:
    Description: App Runner service URL
    Value: !Sub 'https://${AppRunnerService.ServiceUrl}'
    Export:
      Name: !Sub '${AWS::StackName}-ServiceUrl'

  WebhookUrl:
    Description: GitHub webhook URL (update in GitHub App settings)
    Value: !Sub 'https://${AppRunnerService.ServiceUrl}/api/webhooks/github'

  ECRRepositoryUri:
    Description: ECR repository URI for pushing images
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ai-governance'
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepositoryUri'
